{{- include "bjw-s.common.loader.init" . -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bjw-s.common.lib.chart.names.fullname" . }}-pulse
  labels:
    {{- include "bjw-s.common.lib.metadata.allLabels" . | nindent 4 }}
data:
  {{- tpl (.Values.pulse.config | toYaml) $ | nindent 2 }}
