{{- include "bjw-s.common.loader.init" . -}}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "zalando-postgres-cluster.storageClass" . }}
  labels:
    {{- include "bjw-s.common.lib.metadata.allLabels" . | nindent 4 }}
  annotations:
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
