#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
#

# -- log level
log_level: 4

# -- where to send the packages to
backend_hosts:
- "eu1.cloud.thethings.network:1700"

# -- IDs of the gateways sending packages to this server
gateway_ids: []

image:
  # -- image repository
  repository: ghcr.io/angelnu/chirpstack-packet-multiplexer

# -- Configure the services for the chart here.
# @default -- See below.
service:
  main:
    ports:
      http:
        enabled: false
      lorawan:
        enabled: true
        protocol: UDP
        port: 1700
