---
apiVersion: v2
appVersion: v1.8.1
description: |
  Admision controller to change the default gateway and DNS server of PODs.
  It is typically used to route PODs through a VPN server.
name: pod-gateway
version: 6.1.1
kubeVersion: ">=1.16.0-0"
keywords:
  - pod-gateway
home: https://github.com/angelnu/charts/tree/master/charts/stable/pod-gateway
sources:
  - https://github.com/angelnu/gateway-admision-controller
  - https://github.com/angelnu/pod-gateway
icon: https://kubernetes.io/images/wheel.svg
maintainers:
  - name: angelnu
    email: git@angelnu.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.2.1

annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: |
        Add NET_RAW capabilities to pod-gateway for dnsmasq
      links:
        - name: Common library chart definition
          url: https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/Chart.yaml
